### PR TITLE
Cleanup README table of keybindings for jupyter-repl-interaction-mode

### PR DESCRIPTION
**Pull request by non-Jedi**
Sorry for not getting back to you with any comments or questions in issues I've opened. Been very busy. But not too busy to spend 2 minutes quickly fixing up errors I noticed in README.

### CODE REVIEW

**Comment by non-Jedi** [comment]
Actually I see from https://github.com/dzop/emacs-jupyter/blob/669f1716aa7b8f38b900c3dedf40082e8af3358d/jupyter-repl.el#L1631 that the README is out-of-date entirely. I'll circle back around and update the table later if you don't get to it first.

**Comment by dzop** [comment]
Thanks for this. Could open up a new pull request though. Your second commit message says `julia-repl-interaction-mode` instead of `jupyter-repl-interaction-mode`.

**Comment by non-Jedi** [comment]
Ah crud. Sorry about that. I squashed this into a single commit and force pushed that. Commit message should be fine now.

**Comment by dzop** [comment]
Thanks.

**Pull request merged**
